void FONCTION_DU_PETIT_DOIGT_DANS_LE_MODE_BT();
void FONCTION_DE_ANNULAIRE_DANS_LE_MODE_BT();
void FONCTION_DU_MAJEUR_DANS_LE_MODE_BT();
void FONCTION_DE_INDEX_DANS_LE_MODE_BT();
void FONCTION_DU_POUCE_DANS_LE_MODE_BT();